markdown: rdiscount
permalink: /:title/
# url: http://*
name: Scott Ni
author: Scott Ni
# qq:
email: nipengmath@163.com
duoshuo: nipengadmaster
# cnzz: 362173384@qq.com
weiboid: 1213329132
weiboname: Peng Ni
github: nipengadmaster
pygments: true
safe: true
paginate: 20
img_url: https://nipengadmaster.github.com/assets/images
