markdown: rdiscount
permalink: /:title/
# url: http://*
name: Scott Ni
author: Scott Ni
# qq:
email: nipengmath@163.com
duoshuo: nipengadmaster
# cnzz: 362173384@qq.com
weiboid: 1213329132
weiboname: Peng Ni
github: nipengadmaster
pygments: true
safe: true
paginate: 20
about: "<p>我叫倪鹏，数学专业。</p>
<p>目前从事自然语言处理，机器学习，数据挖掘相关工作。</p>
<p>工作经验一年，喜欢专研各种算法理论。主要用python，emacs，在写代码方面还是初学者，争取补强计算机方面知识。</p>
<p>开这个博客是想督促自己学习编程和实践，补强不足，增加战斗力。
努力吧，为了自己！</p>
"

img_url: https://nipengadmaster.github.com/assets/images
